import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

import Header from '@/components/header/header';
import ThemeProvider from '@/components/providers/theme-provider';
import QueryClientProviderWrapper from '@/components/providers/react-query-client-provider';

import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <QueryClientProviderWrapper>
          <ThemeProvider>
            <Header />
            {children}
          </ThemeProvider>
        </QueryClientProviderWrapper>
      </body>
    </html>
  );
}
